services:
  gitopscontainer:
    image: mrtech12/gitops-container:2.4
    container_name: gitops-container
    working_dir: /work
    volumes:
      - ${HOME}:/root
      - ${PWD}:/work
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    stdin_open: true 
    tty: true
    entrypoint: /bin/sh