name: "Deploy to DockerHub"
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "version of docker image"

jobs:
  build-push-docker:
    runs-on: ubuntu-22.04
    steps:
    - name: "checkout project code"
      uses: actions/checkout@v4

    - name: "Login into DockerHub"
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: "build Docker image"
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gitops-container:${{ inputs.version }} .

    - name: "Push Docker image"
      run: docker push ${{ secrets.DOCKER_USERNAME }}/gitops-container:${{ inputs.version }}

    - name: "Tag commit and push"
      run: |
        git tag ${{ inputs.version }}
        git push --tags